name: junit

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with JUnit
        run: |
          mkdir -p out
          javac -d out -cp .:./lib/junit-platform-console-standalone.jar $(find src -name "*.java")
          java -jar ./lib/junit-platform-console-standalone.jar --class-path out --scan-class-path
